apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pbi-generator-data
  labels:
    app: pbi-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
